print("Tämä ohjelma laskee neljän tenttiarvosanan keskiarvon.")
Arvo1 = int(input("Anna 1. tenttiarvosana väliltä 0-5: "))
Arvo2 = int(input("Anna 2. tenttiarvosana väliltä 0-5: "))
Arvo3 = int(input("Anna 3. tenttiarvosana väliltä 0-5: "))
Arvo4 = int(input("Anna 4. tenttiarvosana väliltä 0-5: "))
Summa = int(Arvo1 + Arvo2 + Arvo3 + Arvo4)
KeskiarvoFloat = float(Summa / 4)
KeskiarvoInt = int(KeskiarvoFloat)
print("\n" + "Antamiesi arvosanojen summa on " + str(Summa) + ".")
print("Antamiesi arvosanojen keskiarvo on " + str(round(KeskiarvoFloat,1)) + ".")
print("Keskiarvo on kokonaislukuna " + str(KeskiarvoInt) + ".")
print("Kiitos ohjelman käytöstä.")
